### ISSUE TITLE
Getting Error on Running localhost:8080

### ISSUE THREAD

**Issue by monalv** [rangle/angular2-redux-example#294]
zone.js:516 Unhandled Promise rejection: Token must be defined! ; Zone: <root> ; Task: Promise.then ; Value: ZoneAwareError {__zone_symbol__error: Error: Token must be defined!
    at new ReflectiveKey (http://localhost:8080/app.js:42501:19) [angu…, __zone_symbol__stack: "Error: Token must be defined!↵    at new Reflectiv…(http://localhost:8080/app.js:30938:37) [angular]", __zone_symbol__message: "Token must be defined!"} Error: Token must be defined!
    at new ReflectiveKey (http://localhost:8080/app.js:42501:19) [angular]
    at KeyRegistry.get (http://localhost:8080/app.js:42554:39) [angular]
    at Function.ReflectiveKey.get (http://localhost:8080/app.js:42519:35) [angular]
    at ReflectiveInjector_.get (http://localhost:8080/app.js:82531:102) [angular]
    at RioSampleAppModuleInjector.NgModuleInjector.get (http://localhost:8080/app.js:59937:52) [angular]
    at RouterInitializer.appInitializer (http://localhost:8080/app.js:66868:48) [angular]
    at new ApplicationInitStatus (http://localhost:8080/app.js:40497:45) [angular]
    at RioSampleAppModuleInjector.createInternal (/RioSampleAppModule/module.ngfactory.js:293:36) [angular]
    at RioSampleAppModuleInjector.NgModuleInjector.create (http://localhost:8080/app.js:59920:76) [angular]
    at NgModuleFactory.create (http://localhost:8080/app.js:59888:18) [angular]
    at http://localhost:8080/app.js:40924:61 [angular]
    at Object.onInvoke (http://localhost:8080/app.js:30938:37) [angular]

**Comment by SethDavenport** [comment]
We're in the process of resolving a few transitive dependency issues with the angular toolchain. In the meantime, I suggest using [yarn](http://yarnpkg.com); that way you can benefit from the checked-in `yarn.lock` to use the exact point version's I'm running with.

**Comment by alsh76** [comment]
I got same issue in existing project after `npm install`. It looks like some libraries conflict. Maybe should use exact version numbers in `package.json`? without "~" and "^" I mean
